### ISSUE TITLE
Q: html files with script tags 

### ISSUE THREAD

**Issue by jtn-d** [standard/vscode-standard#10]
Is it possible to enable it for html files with script tags?

**Comment by chenxsan** [comment]
I'm afraid you can't.

**Comment by osdio** [comment]
这个可以支持一下么？

**Comment by osdio** [comment]
目前来说，如果是用vue的，那大量的script都在vue里，我目前是用standard能检查出vue里script的错误，但是不能在vscode中高亮。

**Comment by chenxsan** [comment]
@soliury Standard 能检测 `<script></script>` 里的代码？是用到 https://github.com/feross/standard#can-i-check-code-inside-of-markdown-or-html-files 提到的 eslint-plugin-html 吗？

我看了下 [vscode-eslint 上相关的 issue](https://github.com/Microsoft/vscode-eslint/issues/21)，它已经支持这个特性，后面有时间的话我会 `rebase` 一下。如果你比较着急用这个功能，欢迎提交 pull request :)。

**Comment by osdio** [comment]
对，就是用的eslint-plugin-html插件。
确实比较急用，但是我不知道如何修改额。。。。。。。蛋疼。。。。。

**Comment by chenxsan** [comment]
@soliury hi，我 rebase 了上游的 commit 重新打包了一份，不过因为改动非常大，所以暂时不推到 marketplace 上，你如果想提前试试的话，请安装好 eslint-plugin-html 后下载 https://github.com/chenxsan/vscode-standardjs/blob/master/eslint/vscode-standardjs-1.0.0.vsix 安装，然后在 vscode 的 `settings.json` 文件中配置：

```json
        "standard.validate": [
		"javascript",
		"javascriptreact",
		"html"
	],
	"standard.options": {
            "plugin": ["html"]
	}
```

**Comment by chenxsan** [comment]
@jtn-d Hi, the latest [vscode-standardjs](https://github.com/chenxsan/vscode-standardjs/blob/master/eslint/vscode-standardjs-1.0.0.vsix) already support this feature but it's not pushed to marketplace yet, so if you wanna have a try, please download then install the vsix file after you have `eslint-plugin-html` package installed on your computer. 

And you should modify your vscode `settings.json` file as below to enable the feature:

```json
        "standard.validate": [
		"javascript",
		"javascriptreact",
		"html"
	],
	"standard.options": {
            "plugin": ["html"]
	}
```

**Comment by chenxsan** [comment]
Already push 1.0.9 to marketplace.

**Comment by osdio** [comment]
I have meet this bug in vue:
```
Failed to apply Standard fixes to the document. Please consider opening an issue with steps to reproduce.
```

**Comment by osdio** [comment]
OK, IT is ok now , after I add `vue` to `standard.validate`.
Thank you very much.

**Comment by osdio** [comment]
@chenxsan 我发现一个小bug，就是在vscode里不能格式化vue文件，目前是能高亮出错误，但是不能自动fix，我在命令行执行: `standard --fix`能auto fix，不知道这是不是个bug。

**Comment by chenxsan** [comment]
@soliury 试试这样配置：

```json
	"standard.validate": [
		"javascript",
		"javascriptreact",
		{ "language": "html", "autoFix": true }
	],
```
我估计默认情况下，除了 `javascript` 与 `javascriptreact` 外，其它 language 的 `autoFix` 功能是关闭的。

**Comment by osdio** [comment]
@chenxsan 可以了，感谢。不过对于vue的配置应该是如下：
```
  "standard.validate": [
    "javascript",
    "javascriptreact",
    { "language": "vue", "autoFix": true }
  ],
```

**Comment by chenxsan** [comment]
@soliury VSCode 下默认没有 `vue` 这个 language，所以我是把 .vue 文件的 language 设置为 `html` 了，于是就变成前面那种写法了。

**Comment by osdio** [comment]
@chenxsan 嗦嘎

**Comment by osdio** [comment]
第一次使用vscode，感觉不错哈哈，可以放弃ws了

**Comment by wangduanduan** [comment]
我全局安装eslint-plugin-html后，打开控制台，又报错下面这个，是不是还要全局安装eslint啊？

Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

**Comment by wangduanduan** [comment]
我全局安装eslint后，打开控制台，又报错下面这个?  请问应该怎么配置啊？

[Info  - 20:04:29] JavaScript Standard Style server is running.
[Info  - 20:04:30] JavaScript Standard Style library loaded from: /usr/local/lib/node_modules/standard/index.js
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:62:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:26:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:268:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:62:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:26:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:268:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:62:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:26:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-html/src/index.js:268:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by chenxsan** [comment]
@wangduanduan 如果你的 `eslint-plugin-html` 是全局安装的，则 `standard` 一样要全局安装。

**Comment by chenxsan** [comment]
@Lynn-cc 早期 standard 可以搭配 eslint-plugin-html 插件来检查 vue 文件。但现在 vue 出了官方的 eslint 插件 eslint-plugin-vue，配置的路数不一样了，所以没法再搭配 standard 使用，除非 standard 做些额外扩展 - 显然不大可能：），有兴趣的话，你也可以自己 fork 一个 standard 用 。此外，你可以使用 eslint 初始化一个 standard 风格的配置，就可以用 eslint-plugin-vue 了。
