### ISSUE TITLE
Cannot read property `range` of null

### ISSUE THREAD

**Issue by ospfranco** [standard/vscode-standard#120]
**What version of this package are you using?**
I was using some old versions this morning but I just bumped them and I'm still having the same issues

"standard": "14.3.4"
"eslint": "^7.5.0",

**What operating system, Node.js, and npm version?**
macOS, Node 12, yarn

**What happened?**
I opened my workspace this morning, typed a few things and all of the sudden I have permanent errors that won't go away

```
TypeError: Cannot read property 'range' of null
Occurred while linting /Users/osp/dev/BodyFast/file:/Users/osp/dev/BodyFast/src/Components/FastingPhases.js:258
    at SourceCode.getTokenBefore (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at checkSpacingBefore (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at /Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/osp/dev/BodyFast/node_modules/standard/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23) {
  currentNode: Node {
    type: 'TemplateElement',
    start: 8162,
    end: 8162,
    loc: SourceLocation { start: [Position], end: [Position] },
    range: [ 8162, 8162 ],
    value: { raw: '', cooked: '' },
    tail: false,
    parent: Node {
      type: 'TemplateLiteral',
      start: 8161,
      end: 8181,
      loc: [SourceLocation],
      range: [Array],
      expressions: [Array],
      quasis: [Array],
      parent: [Node]
    }
  }
}
```

The only way to get rid of the parsing errors it to restart vscode (or reload it via command palette), then it works again for a little while, but when I add some text it crashes again

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by ospfranco** [comment]
this comment https://github.com/babel/babel-eslint/issues/530#issuecomment-447511293 on this massive thread seems to have fixed my issue for now
