### ISSUE TITLE
Standard dies after couple of minutes when writing code / Extension cannot format file

### ISSUE THREAD

**Issue by dziku86** [standard/vscode-standard#192]
**What version of this package are you using?**
1.5.0
```
└─┬ standard@16.0.3
  └── standard-engine@14.0.1
```
**What operating system, Node.js, and npm version?**
Windows 6.1 (Build 7601: Service Pack 1) ie32
Node.js 12.21.0
npm 7.6.0

**What happened?**
Extension stops working after couple of minutes when writing code.

Also `Extension  'StandardJS - JavaScript Standard Style' cannot format 'file.js'` error is displayed always when I'm saving file, even when extension is working (errors are displayed and fixed on save).

Also I'm getting this issue https://github.com/standard/vscode-standard/issues/78 .

![image](https://user-images.githubusercontent.com/56586404/113516108-d067a680-9578-11eb-852a-d67b8c547e1b.png)

**What did you expect to happen?**
Extension to work properly.

**Are you willing to submit a pull request to fix this bug?**
No. I am a noob.

**OUTPUT panel:**
```
[Info  - 6:59:56 PM] JavaScript Standard Style server stopped.
[Info  - 7:00:08 PM] JavaScript Standard Style server is running.
[Info  - 7:00:12 PM] JavaScript Standard Style library loaded from: C:\Users\Administrator\AppData\Roaming\npm\node_modules\standard\index.js
```

**VSCode version:**
1.56.0-insider standalone

EDIT:
Forgot to mention that changing `"editor.maxTokenizationLineLength"` number in `settings.json` after extensions death sometimes fixes this issue for a while. :confused:

EDIT:

Just checked VSCode devtools console output:
```
workbench.desktop.main.js:62 [Extension Host] (node:4620) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:32:3))
m @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1613
_doInvokeHandler @ workbench.desktop.main.js:1613
_invokeHandler @ workbench.desktop.main.js:1613
_receiveRequest @ workbench.desktop.main.js:1613
_receiveOneMessage @ workbench.desktop.main.js:1613
(anonymous) @ workbench.desktop.main.js:1613
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
I @ workbench.desktop.main.js:2808
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
```
SO I reverted back to node `9.11.2`  (details here: https://github.com/standard/vscode-standard/issues/124), then disabled all extensions except standard and I didn't get  `Extension  'StandardJS - JavaScript Standard Style' cannot format 'file.js'` error.
Reloaded with standard and [vscode-sftp](https://github.com/liximomo/vscode-sftp) (this extension caused problems before) enabled and got `Buffer()` deprecation warning.
Reloaded again with only standard enabled and extension host crashed (I get this a lot).
SO I think this is an issue with my setup. 
I'm on Windows 7 32bit and I can't update to the latest node because of this npm error:
```
npm ERR! npm ERR! notsup Unsupported platform for node-win-x86@15.12.0: wanted {"os":"win32","arch":"x86"} (current: {"o
s":"win32","arch":"ia32"})
```
It recognizes my os as `ie32` rather than `x86` which is ,quoting wikipedia, "the 32-bit version of the x86 instruction set architecture", so it's npm bug.
SO the problem is my setup. I guess.
This thing is really getting on my nerves for some time now. :weary:

**Comment by dziku86** [comment]
Switched to VSCodium and everything works fine :confused: .
It's not a Standard issue. I'm closing this.

**Comment by dziku86** [comment]
I'm reopening this issue.

Even in VScodium (1.63.2 and 1.60.0) the extensions stops working after 10 - 20 min. Changing some random settings (not related to standard) in `settings.json` somehow 'restarts' extension and it is working again (for some time).

**Comment by theoludwig** [comment]
I don't think this issue is related to this extension.
Have you had issues with other extensions? @dziku86

**Comment by dziku86** [comment]
Other extensions works fine. Even with only standard extension enabled the problem occurs.

**Comment by dziku86** [comment]
When it stops working I get this output in the devtools console:
`workbench.desktop.main.js:577`:
```
  ERR Request got cancelled: Error: Request got cancelled
	at handleResponse (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
```
```
workbench.desktop.main.js:77 [Extension Host] rejected promise not handled within 1 second: undefined
I @ workbench.desktop.main.js:77
$logExtensionHostMessage @ workbench.desktop.main.js:1506
_doInvokeHandler @ workbench.desktop.main.js:1506
_invokeHandler @ workbench.desktop.main.js:1506
_receiveRequest @ workbench.desktop.main.js:1506
_receiveOneMessage @ workbench.desktop.main.js:1506
(anonymous) @ workbench.desktop.main.js:1506
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
O @ workbench.desktop.main.js:2984
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```
`exthost.log` file :
```
[2022-01-31 17:51:32.547] [exthost] [info] Extension host with pid 264 started
[2022-01-31 17:51:32.547] [exthost] [info] Skipping acquiring lock for c:\VSCodium-win32-ia32-1.63.2\data\user-data\User\workspaceStorage\332016385dc099f176da835336587278.
[2022-01-31 17:51:35.273] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-01-31 17:51:35.357] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-01-31 17:51:35.511] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-01-31 17:51:35.599] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*'
[2022-01-31 17:51:35.719] [exthost] [info] ExtensionService#_doActivateExtension standard.vscode-standard, startup: true, activationEvent: '*'
[2022-01-31 17:51:39.489] [exthost] [info] ExtensionService#_doActivateExtension Natizyskunk.sftp, startup: true, activationEvent: 'workspaceContains:.vscode/sftp.json'
[2022-01-31 17:51:41.123] [exthost] [info] Eager extensions activated
[2022-01-31 17:51:41.179] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-01-31 17:51:41.261] [exthost] [info] ExtensionService#_doActivateExtension xyz.local-history, startup: false, activationEvent: 'onStartupFinished'
[2022-01-31 17:54:06.393] [exthost] [error] [standard.vscode-standard] provider FAILED
[2022-01-31 17:54:06.394] [exthost] [error] Error: Request got cancelled
	at handleResponse (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2022-01-31 17:54:06.402] [exthost] [error] [standard.vscode-standard] provider FAILED
[2022-01-31 17:54:06.403] [exthost] [error] Error: Request got cancelled
	at handleResponse (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2022-01-31 18:01:32.416] [exthost] [error] [standard.vscode-standard] provider FAILED
[2022-01-31 18:01:32.417] [exthost] [error] Error: Request got cancelled
	at handleResponse (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\VSCodium-win32-ia32-1.63.2\data\extensions\standard.vscode-standard-2.0.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
```

**Comment by theoludwig** [comment]
Thanks for your detailed report, we'll need to investigate and to know how to reproduce.
