### ISSUE TITLE
vscode-standardjs requires peer-dependency eslint-config-standard and eslint-config-standard-jsx

### ISSUE THREAD

**Issue by lionello** [standard/vscode-standard#57]
When using `pnpm` (instead of `npm`) the below errors are shown in the output panel. These aren't shown when using `npm` because NPM flattens the hierarchy: any nested dependencies can be access by all modules and the app itself, whereas with a module manager like `pnpm` every dependency used had to be explicitly declared.

- StandardJS version: 11.0.0
- VSCode version: Version 1.23.1 (1.23.1) d0182c3417d225529c6d5ad24b7572815d0de9ac
- StandardJS configuration: default
- What do you have in the `OUTPUT` panel:
```
[Info  - 1:15:49 PM] JavaScript Standard Style server is running.
[Info  - 1:15:50 PM] JavaScript Standard Style library loaded from: /repro/node_modules/.registry.npmjs.org/standard/11.0.1/node_modules/standard/index.js
Error: Cannot find module 'eslint-config-standard-jsx'
Referenced from: /repro/node_modules/.registry.npmjs.org/standard/11.0.1/node_modules/standard/eslintrc.json
    at ModuleResolver.resolve (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.loadSpecificConfig (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config.js:139:46)
    at new Config (/repro/node_modules/.registry.npmjs.org/eslint/4.18.2/node_modules/eslint/lib/config.js:101:14)
```

I can fix this error if I explicitly add `eslint-config-standard` and `eslint-config-standard-jsx` to my `package.json`, which in turn requires the following peer deps:
```
 WARN  eslint-config-standard@11.0.0 requires a peer of eslint-plugin-import@>=2.8.0 but none was installed.
 WARN  eslint-config-standard@11.0.0 requires a peer of eslint-plugin-node@>=5.2.1 but none was installed.
 WARN  eslint-config-standard@11.0.0 requires a peer of eslint-plugin-promise@>=3.6.0 but none was installed.
 WARN  eslint-config-standard@11.0.0 requires a peer of eslint-plugin-standard@>=3.0.1 but none was installed.
 WARN  eslint-config-standard-jsx@5.0.0 requires a peer of eslint@>=4.18.0 but none was installed.
 WARN  eslint-config-standard-jsx@5.0.0 requires a peer of eslint-plugin-react@>=7.6.1 but none was installed.
```

So to fix all errors, I had to add the following dev dependencies to my app's `package.json`:
```
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-config-standard-jsx": "^5.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-standard": "^3.1.0",
    "standard": "*"
  },
```

**Comment by stevenmathews** [comment]
@lionello Thanks for this. Recently switched to pnpm.
