### ISSUE TITLE
No linting / error on auto-fix in WSL remote window

### ISSUE THREAD

**Issue by CherryDT** [standard/vscode-standard#89]
When using this extension in a WSL remote window, no linting is done. Executing a command such as "auto-fix problems" shows this error in the "Log (Remote Extension Host)" output panel:

```
[2019-07-06 10:53:18.025] [exthost] [error] Error: Language client is not ready yet
    at LanguageClient.sendRequest (/home/david/.vscode-server-insiders/extensions/chenxsan.vscode-standardjs-1.2.3/client/node_modules/vscode-languageclient/lib/client.js:1465:19)
    at context.subscriptions.push.vscode_1.commands.registerCommand (/home/david/.vscode-server-insiders/extensions/chenxsan.vscode-standardjs-1.2.3/client/src/extension.ts:603:12)
    at f._executeContributedCommand (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:509:714)
    at f.$executeContributedCommand (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:510:104)
    at d._doInvokeHandler (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:663:676)
    at d._invokeHandler (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:663:368)
    at d._receiveRequest (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:662:14)
    at d._receiveOneMessage (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:660:814)
    at _protocol.onMessage.e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:659:34)
    at u.fire (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:48:468)
    at a (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:178:446)
    at e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:178:492)
    at u.fire (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:48:468)
    at e.onMessage.e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:768:875)
    at u.fire (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:48:468)
    at a (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:178:446)
    at e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:178:492)
    at u.fire (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:48:468)
    at y._receiveMessage (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:187:432)
    at _socketDisposables.push._socketReader.onMessage.e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:184:674)
    at u.fire (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:48:468)
    at f.acceptChunk (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:181:234)
    at _register._socket.onData.e (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:180:592)
    at Socket.t (/home/david/.vscode-server-insiders/bin/7e03eb1a1fce3beb6ccea5f3b8f828e01940be61/out/vs/server/remoteExtensionHostProcess.js:188:912)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) standard.executeAutofix
```

This happens even hours after starting, so I doubt that something is really "not ready yet"...

VSCode version:

Version: 1.37.0-insider (system setup)
Commit: 7e03eb1a1fce3beb6ccea5f3b8f828e01940be61
Date: 2019-07-05T18:31:56.611Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

...however it is like this already for many weeks, so it is probably not because of an Insider feature. I've waited with reporting this until the [WSL remote feature made it out of Insiders](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).

(StandardJS version: Irrelevant but it's 12.0.1, JS Standard output panel is empty - I couldn't find any other errors in any of the other output panels except for a "bower.json not found" which I think shouldn't cause anything bad, I don't even use Bower)

**Comment by CherryDT** [comment]
Note: This issue still exists on 1.39.0-insiders...

**Comment by CherryDT** [comment]
Update: Debugging shows that starting the client never finishes, it stays in `ClientState.Starting`. It gets up to the `connection.initialize` call but the callback then never executes.

**Comment by CherryDT** [comment]
Update 2: Adding a delay of 1s before the `connection.initialize` call inside the `vscode-languageclient` solved the problem for me for the moment, but that's of course not a real solution

**Comment by CherryDT** [comment]
Bump - this error still happens. With every update of the extension the error comes back and I have to manually patch it by inserting my 1s delay again.

**Comment by theoludwig** [comment]
Thanks for your bug report! @CherryDT 
Feel free to open a PR to fix this bug. :smile:

**Comment by CherryDT** [comment]
Hm, I'm not sure how to fix it! My workaround is just that - a workaround. And adding code inside a dependency isn't really something a PR can do anyway ^^ It would require somebody who knows how VSCode extensions and language servers and all these things actually work to figure out what's wrong.
